spring:
  main:
    allow-bean-definition-overriding: true
  metrics:
    web:
      autoTimeServerRequests: true
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: admin123
      database: test_db
      port: 27017
      host: localhost
  cloud:
    function:
      definition: person-consumer;person-producer
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
      bindings:
        person-producer-out-0:
          binder: 'rabbit'
          destination: 'fact.person.created'
          group: 'micrometer.metrics'
        person-consumer-in-0:
          binder: 'rabbit'
          destination: 'fact.person.created'
          group: 'micrometer.metrics'

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    br.com.rfasioli: DEBUG
