spring:
  main:
    allow-bean-definition-overriding: true
  metrics:
    web:
      autoTimeServerRequests: true

management:
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include: '*'

info:
  app:
    name: @project.name@
