management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, refresh, prometheus

spring:
  main:
    allow-bean-definition-overriding: true
  metrics:
    web:
      autoTimeServerRequests: true
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: admin123
      database: test_db
      port: 27017
      host: localhost
